version: '3.5'

services:
  #create and run a mongo db instance on backend using this service
  mongodb:
    image: mongo
    restart: always
    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./db:/data/db
    networks:
      - backend
  #Create proxy server
  mongo-proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    restart: always
    networks:
      - backend
#grafana image build using the below service
  grafana:
    build:
      context: .
      dockerfile: grafana/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - backend
      - frontend
volumes:
  db-data:

networks:
  frontend:
    name: frontend-network
  backend:
    name: backend-network
    internal: true
